# Generated by Django 4.2.5 on 2023-09-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_author_date_of_birth_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
